name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            WECHAT_TOKEN
            WECHAT_APP_ID
            WECHAT_APP_SECRET
            WECHAT_USER_ID
            WECHAT_TEMP_ID
        env:
          WECHAT_TOKEN: ${{ secrets.WECHAT_TOKEN}}
          WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID}}
          WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET}}
          WECHAT_USER_ID: ${{ secrets.WECHAT_USER_ID}}
          WECHAT_TEMP_ID: ${{ secrets.WECHAT_TEMP_ID}}
